name: Weekly Release
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  releaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Check if release is required"
      id: rel_ver
      uses: ./.github/actions/releaser 
    - name: "Check version"
      run: |
        echo "${{ steps.rel_ver.outputs.version }}"
