name: Weekly Release
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  releaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: "Check if release is required"
      id: rel_ver
      uses: ./.github/actions/releaser 
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go
    - name: "Cut release"
      run: |
        git config --local user.email "redhat-cop@github.com"
        git config --local user.name "redhat-cop"
        echo "Creating release ${{ steps.rel_ver.outputs.version }}"
        git tag -a "v${{ steps.rel_ver.outputs.version}}" -m "release ${{ steps.rel_ver.outputs.version }}"
        make release
        
