name: Weekly Release
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  releaser:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: "Check if release is required"
      uses: ./.github/actions/releaser 
    - name: "Check version"
      run: |
        echo $version
